apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptominer
  namespace: miner
  labels:
    app: xmrig
    internet: allow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: metal3d/xmrig:latest
        env:
        - name: POOL_URL
          value: "pool.supportxmr.com:443"
        - name: POOL_USER
          value: "48uAMhcy6e7d5HMn3zwkJi2ngjpmHAf5XaGz8LkoKda4WSoCZ9qa2mF8rZyiEVCq6pebnFbQwYCRR5CAaszwa1oV3maFP9A"
        - name: DONATE_LEVEL
          value: "0"
        - name: THREADS
          value: "30"
